language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq libboost-test-dev; fi

compiler:
  - clang
  - gcc

dist: trusty
os:
  # Deactivate linux for now as we need a more modern version of g++ an clang++ than the one in Ubuntu 14.04
  #- linux
  - osx  

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test_hopscotch_map
